/**
 * vertigo - simple java starter
 *
 * Copyright (C) 2013-2018, KleeGroup, direction.technique@kleegroup.com (http://www.kleegroup.com)
 * KleeGroup, Centre d'affaire la Boursidiere - BP 159 - 92357 Le Plessis Robinson Cedex - France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.workflow.dao.instance;

import javax.inject.Inject;

import io.vertigo.app.Home;
import io.vertigo.dynamo.task.metamodel.TaskDefinition;
import io.vertigo.dynamo.task.model.Task;
import io.vertigo.dynamo.task.model.TaskBuilder;
import io.vertigo.dynamo.impl.store.util.DAO;
import io.vertigo.dynamo.store.StoreManager;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.dynamo.task.TaskManager;
import io.vertigo.workflow.domain.instance.WfWorkflow;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class WfWorkflowDAO extends DAO<WfWorkflow, java.lang.Long> implements StoreServices {

	/**
	 * Contructeur.
	 * @param storeManager Manager de persistance
	 * @param taskManager Manager de Task
	 */
	@Inject
	public WfWorkflowDAO(final StoreManager storeManager, final TaskManager taskManager) {
		super(WfWorkflow.class, storeManager, taskManager);
	}


	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Home.getApp().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TK_READ_WORKFLOW_FOR_UPDATE.
	 * @param wfwId Long 
	 * @return io.vertigo.workflow.domain.instance.WfWorkflow workflow
	*/
	public io.vertigo.workflow.domain.instance.WfWorkflow readWorkflowForUpdate(final Long wfwId) {
		final Task task = createTaskBuilder("TK_READ_WORKFLOW_FOR_UPDATE")
				.addValue("WFW_ID", wfwId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_READ_WORKFLOW_INSTANCE_BY_ITEM_ID.
	 * @param wfwdId Long 
	 * @param itemId Long 
	 * @return io.vertigo.workflow.domain.instance.WfWorkflow wfWorkflow
	*/
	public io.vertigo.workflow.domain.instance.WfWorkflow readWorkflowInstanceByItemId(final Long wfwdId, final Long itemId) {
		final Task task = createTaskBuilder("TK_READ_WORKFLOW_INSTANCE_BY_ITEM_ID")
				.addValue("WFWD_ID", wfwdId)
				.addValue("ITEM_ID", itemId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

}
