package io.vertigo.ui.data.domain.fileinfo;

import io.vertigo.core.lang.Generated;
import io.vertigo.datastore.filestore.definitions.FileInfoDefinition;
import io.vertigo.datastore.filestore.model.VFile;
import io.vertigo.datastore.impl.filestore.model.AbstractFileInfo;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class FileInfoTmp extends AbstractFileInfo {
	/** SerialVersionUID. */
	private static final long serialVersionUID = 1L;

	/**
	 * Constructeur par défaut.
	 * @param vFile Données du fichier
	 */
	public FileInfoTmp(final VFile vFile) {
		super(FileInfoDefinition.findFileInfoDefinition(FileInfoTmp.class), vFile);
	}
}
