package io.vertigo.orchestra.dao.run;

import javax.inject.Inject;

import io.vertigo.app.Home;
import io.vertigo.dynamo.task.TaskManager;
import io.vertigo.dynamo.task.metamodel.TaskDefinition;
import io.vertigo.dynamo.task.model.Task;
import io.vertigo.dynamo.task.model.TaskBuilder;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.lang.Assertion;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class RunPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public RunPAO(final TaskManager taskManager) {
		Assertion.checkNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Home.getApp().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TK_INSERT_JOB_EXEC_WITH_JOB_ID.
	 * @param jobExec io.vertigo.orchestra.domain.run.OJobExec 
	*/
	public void insertJobExecWithJobId(final io.vertigo.orchestra.domain.run.OJobExec jobExec) {
		final Task task = createTaskBuilder("TK_INSERT_JOB_EXEC_WITH_JOB_ID")
				.addValue("JOB_EXEC", jobExec)
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TK_INSERT_JOB_RUN_WITH_JOB_ID.
	 * @param jobRun io.vertigo.orchestra.domain.run.OJobRun 
	*/
	public void insertJobRunWithJobId(final io.vertigo.orchestra.domain.run.OJobRun jobRun) {
		final Task task = createTaskBuilder("TK_INSERT_JOB_RUN_WITH_JOB_ID")
				.addValue("JOB_RUN", jobRun)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
