package io.vertigo.orchestra.domain.scheduling;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.URI;
import io.vertigo.dynamo.domain.model.VAccessor;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
@io.vertigo.dynamo.domain.stereotype.DataSpace("orchestra")
public final class OJobSchedule implements Entity {
	private static final long serialVersionUID = 1L;

	private Long jscId;

	private java.time.ZonedDateTime scheduleDate;

	private String params;

	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "A_JSC_JMO",
			fkFieldName = "JMO_ID",
			primaryDtDefinitionName = "DT_O_JOB_MODEL",
			primaryIsNavigable = true,
			primaryRole = "JobModel",
			primaryLabel = "JobModel",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DT_O_JOB_SCHEDULE",
			foreignIsNavigable = false,
			foreignRole = "JobSchedule",
			foreignLabel = "JobSchedule",
			foreignMultiplicity = "0..*")
	private final VAccessor<io.vertigo.orchestra.domain.definition.OJobModel> jmoIdAccessor = new VAccessor<>(io.vertigo.orchestra.domain.definition.OJobModel.class, "jobModel");


	/** {@inheritDoc} */
	@Override
	public URI<OJobSchedule> getURI() {
		return DtObjectUtil.createURI(this);
	}

	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id de la definition de la planification à date'.
	 * @return Long jscId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_IDENTIFIANT", type = "ID", required = true, label = "Id de la definition de la planification à date")
	public Long getJscId() {
		return jscId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id de la definition de la planification à date'.
	 * @param jscId Long <b>Obligatoire</b>
	 */
	public void setJscId(final Long jscId) {
		this.jscId = jscId;
	}
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date d'execution prévue'.
	 * @return java.time.ZonedDateTime scheduleDate
	 */
	@Field(domain = "DO_O_TIMESTAMP", label = "Date d'execution prévue")
	public java.time.ZonedDateTime getScheduleDate() {
		return scheduleDate;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date d'execution prévue'.
	 * @param scheduleDate java.time.ZonedDateTime
	 */
	public void setScheduleDate(final java.time.ZonedDateTime scheduleDate) {
		this.scheduleDate = scheduleDate;
	}
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Paramètres initiaux sous forme de JSON'.
	 * @return String params
	 */
	@Field(domain = "DO_O_JSON_TEXT", label = "Paramètres initiaux sous forme de JSON")
	public String getParams() {
		return params;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Paramètres initiaux sous forme de JSON'.
	 * @param params String
	 */
	public void setParams(final String params) {
		this.params = params;
	}
	
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'JobModel'.
	 * @return Long jmoId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_IDENTIFIANT", type = "FOREIGN_KEY", required = true, label = "JobModel")
	public Long getJmoId() {
		return (Long)  jmoIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'JobModel'.
	 * @param jmoId Long <b>Obligatoire</b>
	 */
	public void setJmoId(final Long jmoId) {
		jmoIdAccessor.setId(jmoId);
	}
	
	/**
	 * Association : JobModel.
	 * @return io.vertigo.orchestra.domain.definition.OJobModel
	 */
				
	public io.vertigo.orchestra.domain.definition.OJobModel getJobModel() {
		return jmoIdAccessor.get();
	}

	/**
	 * Retourne l'URI: JobModel.
	 * @return URI de l'association
	 */
	public io.vertigo.dynamo.domain.model.URI<io.vertigo.orchestra.domain.definition.OJobModel> getJobModelURI() {
		return jmoIdAccessor.getURI();
	}

	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
