package io.vertigo.struts2.data.domain.users;

import io.vertigo.core.lang.Generated;
import io.vertigo.datastore.impl.entitystore.StoreListVAccessor;
import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.dynamo.ngdomain.annotations.Mapper(clazz = io.vertigo.dynamo.domain.util.JsonMapper.class, dataType = io.vertigo.dynamo.domain.metamodel.DataType.String)
public final class SecurityRole implements Entity {
	private static final long serialVersionUID = 1L;

	private String sroCd;
	private String label;

	@io.vertigo.dynamo.domain.stereotype.AssociationNN(
			name = "AnnProSro",
			tableName = "ProSro",
			dtDefinitionA = "DtProfil",
			dtDefinitionB = "DtSecurityRole",
			navigabilityA = false,
			navigabilityB = true,
			roleA = "Profil",
			roleB = "SecurityRole",
			labelA = "Profil",
			labelB = "Security role")
	private final StoreListVAccessor<io.vertigo.struts2.data.domain.users.Profil> profilAccessor = new StoreListVAccessor<>(this, "StAnnProSro", "Profil");

	/** {@inheritDoc} */
	@Override
	public UID<SecurityRole> getUID() {
		return UID.of(this);
	}

	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'SRO_CD'.
	 * @return String sroCd <b>Obligatoire</b>
	 */
	@Field(domain = "STyCode", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "SRO_CD")
	public String getSroCd() {
		return sroCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'SRO_CD'.
	 * @param sroCd String <b>Obligatoire</b>
	 */
	public void setSroCd(final String sroCd) {
		this.sroCd = sroCd;
	}

	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label
	 */
	@Field(domain = "STyLabel", label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}

	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
