package io.vertigo.ui.data.domain.people;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.datamodel.smarttype.annotations.Mapper(clazz = io.vertigo.datamodel.structure.util.JsonMapper.class, dataType = io.vertigo.core.lang.DataType.String)
public final class Casting implements Entity {
	private static final long serialVersionUID = 1L;

	private Long castId;
	private String characterName;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ACastPeo",
			fkFieldName = "peoId",
			primaryDtDefinitionName = "DtPeople",
			primaryIsNavigable = true,
			primaryRole = "People",
			primaryLabel = "People",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtCasting",
			foreignIsNavigable = false,
			foreignRole = "Casting",
			foreignLabel = "Casting",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.ui.data.domain.people.People> peoIdAccessor = new StoreVAccessor<>(io.vertigo.ui.data.domain.people.People.class, "People");

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ACastMov",
			fkFieldName = "movId",
			primaryDtDefinitionName = "DtMovie",
			primaryIsNavigable = true,
			primaryRole = "Movie",
			primaryLabel = "Movie",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtCasting",
			foreignIsNavigable = false,
			foreignRole = "Casting",
			foreignLabel = "Casting",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.ui.data.domain.movies.Movie> movIdAccessor = new StoreVAccessor<>(io.vertigo.ui.data.domain.movies.Movie.class, "Movie");

	/** {@inheritDoc} */
	@Override
	public UID<Casting> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Cast_id'.
	 * @return Long castId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Cast_id")
	public Long getCastId() {
		return castId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Cast_id'.
	 * @param castId Long <b>Obligatoire</b>
	 */
	public void setCastId(final Long castId) {
		this.castId = castId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Character name'.
	 * @return String characterName
	 */
	@Field(smartType = "STyLabelLong", label = "Character name")
	public String getCharacterName() {
		return characterName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Character name'.
	 * @param characterName String
	 */
	public void setCharacterName(final String characterName) {
		this.characterName = characterName;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'People'.
	 * @return Long peoId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "People", fkDefinition = "DtPeople" )
	public Long getPeoId() {
		return (Long) peoIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'People'.
	 * @param peoId Long <b>Obligatoire</b>
	 */
	public void setPeoId(final Long peoId) {
		peoIdAccessor.setId(peoId);
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Movie'.
	 * @return Long movId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyId", label = "Movie", fkDefinition = "DtMovie" )
	public Long getMovId() {
		return (Long) movIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Movie'.
	 * @param movId Long <b>Obligatoire</b>
	 */
	public void setMovId(final Long movId) {
		movIdAccessor.setId(movId);
	}

 	/**
	 * Association : Movie.
	 * @return l'accesseur vers la propriété 'Movie'
	 */
	public StoreVAccessor<io.vertigo.ui.data.domain.movies.Movie> movie() {
		return movIdAccessor;
	}

 	/**
	 * Association : People.
	 * @return l'accesseur vers la propriété 'People'
	 */
	public StoreVAccessor<io.vertigo.ui.data.domain.people.People> people() {
		return peoIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
