package io.vertigo.planning.agenda.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PublicationTrancheHoraireForm implements DtObject {
	private static final long serialVersionUID = 1L;

	private Boolean publishNow;
	private java.time.LocalDate dateLocaleDebut;
	private java.time.LocalDate dateLocaleFin;
	private java.time.LocalDate publicationDateLocale;
	private Integer publicationMinutesDebut;
	private String publicationZonCd;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Publication immediate'.
	 * @return Boolean publishNow
	 */
	@Field(smartType = "STyPBooleen", label = "Publication immediate")
	public Boolean getPublishNow() {
		return publishNow;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Publication immediate'.
	 * @param publishNow Boolean
	 */
	public void setPublishNow(final Boolean publishNow) {
		this.publishNow = publishNow;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date de début'.
	 * @return LocalDate dateLocaleDebut <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date de début")
	public java.time.LocalDate getDateLocaleDebut() {
		return dateLocaleDebut;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date de début'.
	 * @param dateLocaleDebut LocalDate <b>Obligatoire</b>
	 */
	public void setDateLocaleDebut(final java.time.LocalDate dateLocaleDebut) {
		this.dateLocaleDebut = dateLocaleDebut;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date de fin (incluse)'.
	 * @return LocalDate dateLocaleFin <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date de fin (incluse)")
	public java.time.LocalDate getDateLocaleFin() {
		return dateLocaleFin;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date de fin (incluse)'.
	 * @param dateLocaleFin LocalDate <b>Obligatoire</b>
	 */
	public void setDateLocaleFin(final java.time.LocalDate dateLocaleFin) {
		this.dateLocaleFin = dateLocaleFin;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date de publication'.
	 * @return LocalDate publicationDateLocale <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date de publication")
	public java.time.LocalDate getPublicationDateLocale() {
		return publicationDateLocale;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date de publication'.
	 * @param publicationDateLocale LocalDate <b>Obligatoire</b>
	 */
	public void setPublicationDateLocale(final java.time.LocalDate publicationDateLocale) {
		this.publicationDateLocale = publicationDateLocale;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Heure de publication'.
	 * @return Integer publicationMinutesDebut <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPHeureMinute", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Heure de publication")
	public Integer getPublicationMinutesDebut() {
		return publicationMinutesDebut;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Heure de publication'.
	 * @param publicationMinutesDebut Integer <b>Obligatoire</b>
	 */
	public void setPublicationMinutesDebut(final Integer publicationMinutesDebut) {
		this.publicationMinutesDebut = publicationMinutesDebut;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Fuseau horaire publication'.
	 * @return String publicationZonCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPCode", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Fuseau horaire publication")
	public String getPublicationZonCd() {
		return publicationZonCd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Fuseau horaire publication'.
	 * @param publicationZonCd String <b>Obligatoire</b>
	 */
	public void setPublicationZonCd(final String publicationZonCd) {
		this.publicationZonCd = publicationZonCd;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
