package io.vertigo.orchestra.domain.model;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.URI;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.dynamo.domain.stereotype.DataSpace("orchestra")
public final class OJobModel implements Entity {
	private static final long serialVersionUID = 1L;

	private Long jmoId;

	private String jobname;

	private String desc;

	private String classEngine;

	private Integer maxRetry;

	private Integer maxDelay;

	private Integer timeout;

	private java.time.ZonedDateTime creationDate;

	private Boolean active;


	/** {@inheritDoc} */
	@Override
	public URI<OJobModel> getURI() {
		return DtObjectUtil.createURI(this);
	}

	
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'id'.
	 * @return Long jmoId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_IDENTIFIANT", type = "ID", required = true, label = "id")
	public Long getJmoId() {
		return jmoId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'id'.
	 * @param jmoId Long <b>Obligatoire</b>
	 */
	
	public void setJmoId(final Long jmoId) {
		this.jmoId = jmoId;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String jobname
	 */
	@Field(domain = "DO_O_LABEL", label = "Name")
	public String getJobname() {
		return jobname;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param jobname String
	 */
	
	public void setJobname(final String jobname) {
		this.jobname = jobname;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Description'.
	 * @return String desc
	 */
	@Field(domain = "DO_O_LABEL", label = "Description")
	public String getDesc() {
		return desc;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Description'.
	 * @param desc String
	 */
	
	public void setDesc(final String desc) {
		this.desc = desc;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Class of the Job'.
	 * @return String classEngine
	 */
	@Field(domain = "DO_O_CLASS", label = "Class of the Job")
	public String getClassEngine() {
		return classEngine;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Class of the Job'.
	 * @param classEngine String
	 */
	
	public void setClassEngine(final String classEngine) {
		this.classEngine = classEngine;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'max retry limit'.
	 * @return Integer maxRetry
	 */
	@Field(domain = "DO_O_INTEGER", label = "max retry limit")
	public Integer getMaxRetry() {
		return maxRetry;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'max retry limit'.
	 * @param maxRetry Integer
	 */
	
	public void setMaxRetry(final Integer maxRetry) {
		this.maxRetry = maxRetry;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Max delay of all executions'.
	 * @return Integer maxDelay
	 */
	@Field(domain = "DO_O_INTEGER", label = "Max delay of all executions")
	public Integer getMaxDelay() {
		return maxDelay;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Max delay of all executions'.
	 * @param maxDelay Integer
	 */
	
	public void setMaxDelay(final Integer maxDelay) {
		this.maxDelay = maxDelay;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Max delay of a single execution'.
	 * @return Integer timeout
	 */
	@Field(domain = "DO_O_INTEGER", label = "Max delay of a single execution")
	public Integer getTimeout() {
		return timeout;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Max delay of a single execution'.
	 * @param timeout Integer
	 */
	
	public void setTimeout(final Integer timeout) {
		this.timeout = timeout;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'creation date'.
	 * @return java.time.ZonedDateTime creationDate
	 */
	@Field(domain = "DO_O_TIMESTAMP", label = "creation date")
	public java.time.ZonedDateTime getCreationDate() {
		return creationDate;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'creation date'.
	 * @param creationDate java.time.ZonedDateTime
	 */
	
	public void setCreationDate(final java.time.ZonedDateTime creationDate) {
		this.creationDate = creationDate;
	}
	
	
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Active/Inactive'.
	 * @return Boolean active
	 */
	@Field(domain = "DO_O_BOOLEAN", label = "Active/Inactive")
	public Boolean getActive() {
		return active;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Active/Inactive'.
	 * @param active Boolean
	 */
	
	public void setActive(final Boolean active) {
		this.active = active;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
