package io.vertigo.orchestra.domain.run;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.URI;
import io.vertigo.dynamo.domain.model.VAccessor;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.dynamo.domain.stereotype.DataSpace("orchestra")
public final class OJobRun implements Entity {
	private static final long serialVersionUID = 1L;

	private String jobId;
	private String jexId;
	private Boolean alive;
	private String status;
	private Integer currentTry;
	private java.time.Instant startInstant;
	private java.time.Instant maxInstant;
	private Integer maxRetry;

	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "A_JRN_JMO",
			fkFieldName = "JMO_ID",
			primaryDtDefinitionName = "DT_O_JOB_MODEL",
			primaryIsNavigable = true,
			primaryRole = "JobModel",
			primaryLabel = "JobModel",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DT_O_JOB_RUN",
			foreignIsNavigable = false,
			foreignRole = "JobRun",
			foreignLabel = "JobRun",
			foreignMultiplicity = "0..*")
	private final VAccessor<io.vertigo.orchestra.domain.model.OJobModel> jmoIdAccessor = new VAccessor<>(io.vertigo.orchestra.domain.model.OJobModel.class, "JobModel");

	/** {@inheritDoc} */
	@Override
	public URI<OJobRun> getURI() {
		return DtObjectUtil.createURI(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String jobId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_JOB_IDENTIFIANT", type = "ID", required = true, label = "Id")
	public String getJobId() {
		return jobId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param jobId String <b>Obligatoire</b>
	 */
	public void setJobId(final String jobId) {
		this.jobId = jobId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Exec UUID'.
	 * @return String jexId
	 */
	@Field(domain = "DO_O_UUID", label = "Exec UUID")
	public String getJexId() {
		return jexId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Exec UUID'.
	 * @param jexId String
	 */
	public void setJexId(final String jexId) {
		this.jexId = jexId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'alive y/n'.
	 * @return Boolean alive <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_BOOLEAN", required = true, label = "alive y/n")
	public Boolean getAlive() {
		return alive;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'alive y/n'.
	 * @param alive Boolean <b>Obligatoire</b>
	 */
	public void setAlive(final Boolean alive) {
		this.alive = alive;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Exec status'.
	 * @return String status <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_STATUS_CODE", required = true, label = "Exec status")
	public String getStatus() {
		return status;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Exec status'.
	 * @param status String <b>Obligatoire</b>
	 */
	public void setStatus(final String status) {
		this.status = status;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Current try'.
	 * @return Integer currentTry <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_INTEGER", required = true, label = "Current try")
	public Integer getCurrentTry() {
		return currentTry;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Current try'.
	 * @param currentTry Integer <b>Obligatoire</b>
	 */
	public void setCurrentTry(final Integer currentTry) {
		this.currentTry = currentTry;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Start date of the run'.
	 * @return java.time.Instant startInstant <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_TIMESTAMP", required = true, label = "Start date of the run")
	public java.time.Instant getStartInstant() {
		return startInstant;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Start date of the run'.
	 * @param startInstant java.time.Instant <b>Obligatoire</b>
	 */
	public void setStartInstant(final java.time.Instant startInstant) {
		this.startInstant = startInstant;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Max date of the run'.
	 * @return java.time.Instant maxInstant <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_TIMESTAMP", required = true, label = "Max date of the run")
	public java.time.Instant getMaxInstant() {
		return maxInstant;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Max date of the run'.
	 * @param maxInstant java.time.Instant <b>Obligatoire</b>
	 */
	public void setMaxInstant(final java.time.Instant maxInstant) {
		this.maxInstant = maxInstant;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Max retry'.
	 * @return Integer maxRetry <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_INTEGER", required = true, label = "Max retry")
	public Integer getMaxRetry() {
		return maxRetry;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Max retry'.
	 * @param maxRetry Integer <b>Obligatoire</b>
	 */
	public void setMaxRetry(final Integer maxRetry) {
		this.maxRetry = maxRetry;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'JobModel'.
	 * @return Long jmoId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_O_IDENTIFIANT", type = "FOREIGN_KEY", required = true, label = "JobModel")
	public Long getJmoId() {
		return (Long)  jmoIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'JobModel'.
	 * @param jmoId Long <b>Obligatoire</b>
	 */
	public void setJmoId(final Long jmoId) {
		jmoIdAccessor.setId(jmoId);
	}

 	/**
	 * Association : JobModel.
	 * @return l'accesseur vers la propriété 'JobModel'
	 */
	public VAccessor<io.vertigo.orchestra.domain.model.OJobModel> jobModel() {
		return jmoIdAccessor;
	}
	
	@Deprecated
	public io.vertigo.orchestra.domain.model.OJobModel getJobModel() {
		// we keep the lazyness
		if (!jmoIdAccessor.isLoaded()) {
			jmoIdAccessor.load();
		}
		return jmoIdAccessor.get();
	}

	/**
	 * Retourne l'URI: JobModel.
	 * @return URI de l'association
	 */
	@Deprecated
	public io.vertigo.dynamo.domain.model.URI<io.vertigo.orchestra.domain.model.OJobModel> getJobModelURI() {
		return jmoIdAccessor.getURI();
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
