package io.vertigo.ui.data.dao.movies;

import java.util.List;

import javax.inject.Inject;

import io.vertigo.app.Home;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.dynamo.task.TaskManager;
import io.vertigo.dynamo.task.metamodel.TaskDefinition;
import io.vertigo.dynamo.task.model.Task;
import io.vertigo.dynamo.task.model.TaskBuilder;
import io.vertigo.lang.Assertion;
import io.vertigo.lang.Generated;
import io.vertigo.ui.data.domain.movies.MovieIndex;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MoviesPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public MoviesPAO(final TaskManager taskManager) {
		Assertion.checkNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Home.getApp().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TK_LOAD_MOVIE_INDEX.
	 * @param dtc io.vertigo.dynamo.domain.model.DtList<io.vertigo.pandora.domain.movies.Dummy>
	 * @return io.vertigo.dynamo.domain.model.DtList<io.vertigo.pandora.domain.movies.MovieIndex> dtcIndex
	*/
	public io.vertigo.dynamo.domain.model.DtList<MovieIndex> loadMovieIndex(final List<Long> movieIds) {
		final Task task = createTaskBuilder("TK_LOAD_MOVIE_INDEX")
				.addValue("MOVIE_IDS", movieIds)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_REMOVE_ALL_ACTOR_ROLES.
	*/
	public void removeAllActorRoles() {
		final Task task = createTaskBuilder("TK_REMOVE_ALL_ACTOR_ROLES")
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TK_REMOVE_ALL_MOVIES.
	*/
	public void removeAllMovies() {
		final Task task = createTaskBuilder("TK_REMOVE_ALL_MOVIES")
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
