
ALTER TABLE O_ACTIVITY ALTER PRO_ID SET NOT NULL;

ALTER TABLE O_ACTIVITY_EXECUTION ALTER ACT_ID SET NOT NULL;
ALTER TABLE O_ACTIVITY_EXECUTION ALTER PRE_ID SET NOT NULL;
ALTER TABLE O_ACTIVITY_EXECUTION ALTER NOD_ID SET NOT NULL;
ALTER TABLE O_ACTIVITY_EXECUTION ALTER EST_CD SET NOT NULL;

ALTER TABLE O_ACTIVITY_LOG ALTER ACE_ID SET NOT NULL;

ALTER TABLE O_ACTIVITY_WORKSPACE ALTER ACE_ID SET NOT NULL;

ALTER TABLE O_PROCESS ALTER TRT_CD SET NOT NULL;

ALTER TABLE O_PROCESS_EXECUTION ALTER PRO_ID SET NOT NULL;

ALTER TABLE O_PROCESS_PLANIFICATION ALTER PRO_ID SET NOT NULL;
