package io.vertigo.easyforms.metaformulaire.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Taxonomie implements Entity {
	private static final long serialVersionUID = 1L;

	private Long taxId;
	private String value;
	private Integer sort;
	private Boolean active;

	@io.vertigo.datamodel.structure.stereotype.Association(
			name = "ATaxonomieValueType",
			fkFieldName = "tatId",
			primaryDtDefinitionName = "DtTaxonomieType",
			primaryIsNavigable = true,
			primaryRole = "TaxonomieType",
			primaryLabel = "Taxonomie type",
			primaryMultiplicity = "1..1",
			foreignDtDefinitionName = "DtTaxonomie",
			foreignIsNavigable = false,
			foreignRole = "Taxonomie",
			foreignLabel = "Taxonomie",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.easyforms.metaformulaire.domain.TaxonomieType> tatIdAccessor = new StoreVAccessor<>(io.vertigo.easyforms.metaformulaire.domain.TaxonomieType.class, "TaxonomieType");

	/** {@inheritDoc} */
	@Override
	public UID<Taxonomie> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long taxId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyFId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getTaxId() {
		return taxId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param taxId Long <b>Obligatoire</b>
	 */
	public void setTaxId(final Long taxId) {
		this.taxId = taxId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Valeur'.
	 * @return String value
	 */
	@Field(smartType = "STyFLabel", label = "Valeur")
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getValue() {
		return value;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Valeur'.
	 * @param value String
	 */
	public void setValue(final String value) {
		this.value = value;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Ordre'.
	 * @return Integer sort <b>Obligatoire</b>
	 */
	@Field(smartType = "STyFSort", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Ordre")
	@io.vertigo.datamodel.structure.stereotype.SortField
	public Integer getSort() {
		return sort;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Ordre'.
	 * @param sort Integer <b>Obligatoire</b>
	 */
	public void setSort(final Integer sort) {
		this.sort = sort;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Actif'.
	 * @return Boolean active <b>Obligatoire</b>
	 */
	@Field(smartType = "STyFBooleen", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Actif")
	public Boolean getActive() {
		return active;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Actif'.
	 * @param active Boolean <b>Obligatoire</b>
	 */
	public void setActive(final Boolean active) {
		this.active = active;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Taxonomie type'.
	 * @return Long tatId <b>Obligatoire</b>
	 */
	@io.vertigo.datamodel.structure.stereotype.ForeignKey(smartType = "STyFId", label = "Taxonomie type", fkDefinition = "DtTaxonomieType", cardinality = io.vertigo.core.lang.Cardinality.ONE )
	public Long getTatId() {
		return (Long) tatIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Taxonomie type'.
	 * @param tatId Long <b>Obligatoire</b>
	 */
	public void setTatId(final Long tatId) {
		tatIdAccessor.setId(tatId);
	}

 	/**
	 * Association : Taxonomie type.
	 * @return l'accesseur vers la propriété 'Taxonomie type'
	 */
	public StoreVAccessor<io.vertigo.easyforms.metaformulaire.domain.TaxonomieType> taxonomieType() {
		return tatIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
