/*
 * vertigo - application development platform
 *
 * Copyright (C) 2013-2023, Vertigo.io, team@vertigo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.orchestra.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.definitions.DtFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données OActivity. */
		OActivity(io.vertigo.orchestra.domain.definition.OActivity.class),
		/** Objet de données OActivityExecution. */
		OActivityExecution(io.vertigo.orchestra.domain.execution.OActivityExecution.class),
		/** Objet de données OActivityExecutionUi. */
		OActivityExecutionUi(io.vertigo.orchestra.monitoring.domain.uiexecutions.OActivityExecutionUi.class),
		/** Objet de données OActivityLog. */
		OActivityLog(io.vertigo.orchestra.domain.execution.OActivityLog.class),
		/** Objet de données OActivityWorkspace. */
		OActivityWorkspace(io.vertigo.orchestra.domain.execution.OActivityWorkspace.class),
		/** Objet de données OExecutionState. */
		OExecutionState(io.vertigo.orchestra.domain.referential.OExecutionState.class),
		/** Objet de données OExecutionSummary. */
		OExecutionSummary(io.vertigo.orchestra.monitoring.domain.summary.OExecutionSummary.class),
		/** Objet de données ONode. */
		ONode(io.vertigo.orchestra.domain.execution.ONode.class),
		/** Objet de données OProcess. */
		OProcess(io.vertigo.orchestra.domain.definition.OProcess.class),
		/** Objet de données OProcessExecution. */
		OProcessExecution(io.vertigo.orchestra.domain.execution.OProcessExecution.class),
		/** Objet de données OProcessExecutionUi. */
		OProcessExecutionUi(io.vertigo.orchestra.monitoring.domain.uiexecutions.OProcessExecutionUi.class),
		/** Objet de données OProcessPlanification. */
		OProcessPlanification(io.vertigo.orchestra.domain.planification.OProcessPlanification.class),
		/** Objet de données OProcessType. */
		OProcessType(io.vertigo.orchestra.domain.referential.OProcessType.class),
		/** Objet de données OProcessUi. */
		OProcessUi(io.vertigo.orchestra.monitoring.domain.uidefinitions.OProcessUi.class),
		/** Objet de données OSchedulerState. */
		OSchedulerState(io.vertigo.orchestra.domain.referential.OSchedulerState.class),
		/** Objet de données OUser. */
		OUser(io.vertigo.orchestra.domain.referential.OUser.class),
		/** Objet de données TriggerType. */
		TriggerType(io.vertigo.orchestra.domain.referential.TriggerType.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de OActivity.
	 */
	public enum OActivityFields implements DtFieldName<io.vertigo.orchestra.domain.definition.OActivity> {
		/** Propriété 'Id Activité'. */
		actId,
		/** Propriété 'Nom de l'activité'. */
		name,
		/** Propriété 'Libellé de l'activité'. */
		label,
		/** Propriété 'Numéro de l'activité'. */
		number,
		/** Propriété 'Jalon'. */
		milestone,
		/** Propriété 'Implémentation de l'activité'. */
		engine,
		/** Propriété 'Processus'. */
		proId	}

	/**
	 * Enumération des champs de OActivityExecution.
	 */
	public enum OActivityExecutionFields implements DtFieldName<io.vertigo.orchestra.domain.execution.OActivityExecution> {
		/** Propriété 'Id de l'execution d'un processus'. */
		aceId,
		/** Propriété 'Date de création'. */
		creationTime,
		/** Propriété 'Date de début'. */
		beginTime,
		/** Propriété 'Date de fin'. */
		endTime,
		/** Propriété 'Implémentation effective de l'execution'. */
		engine,
		/** Propriété 'Token d'identification'. */
		token,
		/** Propriété 'Activity'. */
		actId,
		/** Propriété 'Processus'. */
		preId,
		/** Propriété 'Node'. */
		nodId,
		/** Propriété 'ExecutionState'. */
		estCd	}

	/**
	 * Enumération des champs de OActivityExecutionUi.
	 */
	public enum OActivityExecutionUiFields implements DtFieldName<io.vertigo.orchestra.monitoring.domain.uiexecutions.OActivityExecutionUi> {
		/** Propriété 'Id de l'activité'. */
		aceId,
		/** Propriété 'Libellé'. */
		label,
		/** Propriété 'Démarrage'. */
		beginTime,
		/** Propriété 'Fin'. */
		endTime,
		/** Propriété 'Durée'. */
		executionTime,
		/** Propriété 'Statut'. */
		status,
		/** Propriété 'Paramètres entrants'. */
		workspaceIn,
		/** Propriété 'Paramètres sortants'. */
		workspaceOut,
		/** Propriété 'Fichier de log'. */
		hasAttachment,
		/** Propriété 'Log technique'. */
		hasTechnicalLog	}

	/**
	 * Enumération des champs de OActivityLog.
	 */
	public enum OActivityLogFields implements DtFieldName<io.vertigo.orchestra.domain.execution.OActivityLog> {
		/** Propriété 'Id du log'. */
		aclId,
		/** Propriété 'Contenu du log'. */
		log,
		/** Propriété 'Fichier joint'. */
		attachment,
		/** Propriété 'ActivityExecution'. */
		aceId	}

	/**
	 * Enumération des champs de OActivityWorkspace.
	 */
	public enum OActivityWorkspaceFields implements DtFieldName<io.vertigo.orchestra.domain.execution.OActivityWorkspace> {
		/** Propriété 'Id de l'execution d'un processus'. */
		acwId,
		/** Propriété 'Workspace in/out'. */
		isIn,
		/** Propriété 'Contenu du workspace'. */
		workspace,
		/** Propriété 'ActivityExecution'. */
		aceId	}

	/**
	 * Enumération des champs de OExecutionState.
	 */
	public enum OExecutionStateFields implements DtFieldName<io.vertigo.orchestra.domain.referential.OExecutionState> {
		/** Propriété 'Code'. */
		estCd,
		/** Propriété 'Libellé'. */
		label	}

	/**
	 * Enumération des champs de OExecutionSummary.
	 */
	public enum OExecutionSummaryFields implements DtFieldName<io.vertigo.orchestra.monitoring.domain.summary.OExecutionSummary> {
		/** Propriété 'Id du processus'. */
		proId,
		/** Propriété 'Nom du processus'. */
		processName,
		/** Propriété 'Libellé du processus'. */
		processLabel,
		/** Propriété 'Dernière exécution le'. */
		lastExecutionTime,
		/** Propriété 'Prochaine exécution le'. */
		nextExecutionTime,
		/** Propriété 'Nombre en erreur'. */
		errorsCount,
		/** Propriété 'Nombre non executés'. */
		misfiredCount,
		/** Propriété 'Nombre en succès'. */
		successfulCount,
		/** Propriété 'Nombre en cours'. */
		runningCount,
		/** Propriété 'Durée moyenne d'exécution'. */
		averageExecutionTime,
		/** Propriété 'Santé du processus'. */
		health	}

	/**
	 * Enumération des champs de ONode.
	 */
	public enum ONodeFields implements DtFieldName<io.vertigo.orchestra.domain.execution.ONode> {
		/** Propriété 'Id du noeud'. */
		nodId,
		/** Propriété 'Nom du noeud'. */
		name,
		/** Propriété 'Date de dernière activité'. */
		heartbeat	}

	/**
	 * Enumération des champs de OProcess.
	 */
	public enum OProcessFields implements DtFieldName<io.vertigo.orchestra.domain.definition.OProcess> {
		/** Propriété 'Id de la definition du processus'. */
		proId,
		/** Propriété 'Nom du processus'. */
		name,
		/** Propriété 'Libellé du processus'. */
		label,
		/** Propriété 'Expression récurrence du processus'. */
		cronExpression,
		/** Propriété 'Paramètres initiaux sous forme de JSON'. */
		initialParams,
		/** Propriété 'Accepte la multi-execution'. */
		multiexecution,
		/** Propriété 'Version active'. */
		activeVersion,
		/** Propriété 'Processus actif'. */
		active,
		/** Propriété 'Temps de validité d'une planification'. */
		rescuePeriod,
		/** Propriété 'Meta-données du processus'. */
		metadatas,
		/** Propriété 'Doit être mise à jour lors du démarrage'. */
		needUpdate,
		/** Propriété 'TriggerType'. */
		trtCd,
		/** Propriété 'ProcessType'. */
		prtCd	}

	/**
	 * Enumération des champs de OProcessExecution.
	 */
	public enum OProcessExecutionFields implements DtFieldName<io.vertigo.orchestra.domain.execution.OProcessExecution> {
		/** Propriété 'Id de l'execution d'un processus'. */
		preId,
		/** Propriété 'Date de début'. */
		beginTime,
		/** Propriété 'Date de fin'. */
		endTime,
		/** Propriété 'Implémentation effective de l'execution'. */
		engine,
		/** Propriété 'Pris en charge'. */
		checked,
		/** Propriété 'Date de prise en charge'. */
		checkingDate,
		/** Propriété 'Commentaire'. */
		checkingComment,
		/** Propriété 'Processus'. */
		proId,
		/** Propriété 'ExecutionState'. */
		estCd,
		/** Propriété 'User'. */
		usrId	}

	/**
	 * Enumération des champs de OProcessExecutionUi.
	 */
	public enum OProcessExecutionUiFields implements DtFieldName<io.vertigo.orchestra.monitoring.domain.uiexecutions.OProcessExecutionUi> {
		/** Propriété 'Id de l'activité'. */
		preId,
		/** Propriété 'Démarrage'. */
		beginTime,
		/** Propriété 'Fin'. */
		endTime,
		/** Propriété 'Durée'. */
		executionTime,
		/** Propriété 'Statut'. */
		status,
		/** Propriété 'Pris en charge'. */
		checked,
		/** Propriété 'Date de prise en charge'. */
		checkingDate,
		/** Propriété 'Commentaire'. */
		checkingComment,
		/** Propriété 'Fichier de log'. */
		hasAttachment	}

	/**
	 * Enumération des champs de OProcessPlanification.
	 */
	public enum OProcessPlanificationFields implements DtFieldName<io.vertigo.orchestra.domain.planification.OProcessPlanification> {
		/** Propriété 'Id Planification'. */
		prpId,
		/** Propriété 'Date d'execution prévue'. */
		expectedTime,
		/** Propriété 'Paramètres initiaux sous forme de JSON'. */
		initialParams,
		/** Propriété 'Processus'. */
		proId,
		/** Propriété 'Node'. */
		nodId,
		/** Propriété 'PlanificationState'. */
		sstCd	}

	/**
	 * Enumération des champs de OProcessType.
	 */
	public enum OProcessTypeFields implements DtFieldName<io.vertigo.orchestra.domain.referential.OProcessType> {
		/** Propriété 'Code'. */
		prtCd,
		/** Propriété 'Libellé'. */
		label	}

	/**
	 * Enumération des champs de OProcessUi.
	 */
	public enum OProcessUiFields implements DtFieldName<io.vertigo.orchestra.monitoring.domain.uidefinitions.OProcessUi> {
		/** Propriété 'Id du processus'. */
		proId,
		/** Propriété 'Nom du processus'. */
		name,
		/** Propriété 'Libellé du processus'. */
		label,
		/** Propriété 'Expression récurrence du processus'. */
		cronExpression,
		/** Propriété 'Paramètres initiaux sous forme de JSON'. */
		initialParams,
		/** Propriété 'Accepte la multi-execution'. */
		multiexecution,
		/** Propriété 'Processus actif'. */
		active,
		/** Propriété 'Temps de validité d'une planification'. */
		rescuePeriod,
		/** Propriété 'Métadonnées du processus'. */
		metadatas	}

	/**
	 * Enumération des champs de OSchedulerState.
	 */
	public enum OSchedulerStateFields implements DtFieldName<io.vertigo.orchestra.domain.referential.OSchedulerState> {
		/** Propriété 'Code'. */
		sstCd,
		/** Propriété 'Libellé'. */
		label	}

	/**
	 * Enumération des champs de OUser.
	 */
	public enum OUserFields implements DtFieldName<io.vertigo.orchestra.domain.referential.OUser> {
		/** Propriété 'Id'. */
		usrId,
		/** Propriété 'Nom'. */
		firstName,
		/** Propriété 'Prénom'. */
		lastName,
		/** Propriété 'Email'. */
		email,
		/** Propriété 'Mot de passe'. */
		password,
		/** Propriété 'Alerté en cas d'erreur'. */
		mailAlert,
		/** Propriété 'Compte Actif'. */
		active	}

	/**
	 * Enumération des champs de TriggerType.
	 */
	public enum TriggerTypeFields implements DtFieldName<io.vertigo.orchestra.domain.referential.TriggerType> {
		/** Propriété 'Code'. */
		trtCd,
		/** Propriété 'Libellé'. */
		label	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
