package io.vertigo.ui.impl.jetty.multipart;

import java.io.IOException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.eclipse.jetty.ee10.servlet.ServletContextRequest;
import org.eclipse.jetty.http.HttpHeader;
import org.eclipse.jetty.http.HttpMethod;
import org.eclipse.jetty.http.MultiPartFormData;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;
import org.eclipse.jetty.util.Callback;

import jakarta.servlet.MultipartConfigElement;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Handler that adds the multipart config to the request that passes through if
 * it is a multipart request.
 * <p>
 * Jetty will only clean up the temp files generated by
 * request is about to die but won't invoke it for a non-servlet (webapp)
 * handled request.
 * <p>
 * MultipartConfigInjectionHandler ensures that the parts are deleted after the
 * {@link #handle(String, Request, HttpServletRequest, HttpServletResponse)}
 * method is called.
 * <p>
 * Ensure that no other handlers sit above this handler which may wish to do
 * something with the multipart parts, as the saved parts will be deleted on the return
 * from
 * {@link #handle(String, Request, HttpServletRequest, HttpServletResponse)}.
 */
public class JettyMultipartHandlerWrapper extends Handler.Wrapper {
	private static final Logger LOG = LogManager.getLogger(JettyMultipartHandlerWrapper.class);
	private static final String MULTIPART_FORMDATA_TYPE = "multipart/form-data";
	private final MultipartConfigElement multiPartConfigElement;

	public JettyMultipartHandlerWrapper(
			final String location,
			final int maxPartSizeMb,
			final int maxRequestSize,
			final int maxPartSizeInMemoryKb) {
		this.multiPartConfigElement = new MultipartConfigElement(
				location,
				maxPartSizeMb * 1024 * 1024,
				maxRequestSize * 1024 * 1024,
				maxPartSizeInMemoryKb * 1024);
	}

	public static boolean isMultipartRequest(final Request request) {
		return request.getHeaders().get(HttpHeader.CONTENT_TYPE) != null
				&& request.getHeaders().get(HttpHeader.CONTENT_TYPE).startsWith(MULTIPART_FORMDATA_TYPE);
	}

	@Override
	public boolean handle(final Request request, final Response response, final Callback callback) throws Exception {
		final var multipartRequest = HttpMethod.POST.is(request.getMethod()) && isMultipartRequest(request);
		if (multipartRequest) {
			//enableMultipartSupport
			request.setAttribute(ServletContextRequest.MULTIPART_CONFIG_ELEMENT, multiPartConfigElement);
		}

		try {
			return super.handle(request, response, callback);
		} finally {
			if (multipartRequest) {
				MultiPartFormData.Parts multiParts;
				multiParts = MultiPartFormData.getParts(request);
				if (multiParts != null && multiParts.size() > 0) {
					multiParts.forEach(part -> {
						try {
							// a multipart request to a servlet will have the parts cleaned up correctly, but
							// the repeated call to deleteParts() here will safely do nothing.
							part.delete();
						} catch (final IOException e) {
							LOG.warn("Error while deleting multipart request parts", e);
						}
					});
				}
			}
			callback.succeeded();
		}
	}
}
